### ISSUE TITLE
Close Fulfilled  Icon Requests

### ISSUE THREAD

**Issue by nonnominandus** [dkanada/frost#213] opened 2019-10-30 21:58 UTC
When I was searching for icon request to draw today I saw some request that were finished that are still open. I think closing these would help in manageability of all issues and would invite new people to submit requests (open requests of a couple years ago could let people down). I hope to add a list of closable requests soon.

**Comment by dkanada** [comment] 2019-10-31 02:06
I agree, and I try to when all icons have been added but sometimes only a portion of the icons get added. If you list any here that are completely finished I will close them.

**Comment by Donnnno** [comment] 2019-11-20 17:30
I've created some lists with all created and missing icons in these issues: #2 #4 #11 and #74 . I kinda under estimated the time this takes to do. :/

**Comment by h-bruch** [comment] 2019-11-20 17:45
Nice! That will make things a bit easier, when looking through old issues.

@dkanada What is your preferred way to notify you of issues that can be closed? Mentioning it in the pull request?

**Comment by Donnnno** [comment] 2019-11-20 18:57
#18 can be closed

**Comment by dkanada** [comment] 2019-11-21 03:59
> I kinda under estimated the time this takes to do.

Creating lists or designing icons? You can mention issues here since there are so many. Once the count goes down I will probably close this one and then just track everything from the individual issues again.

**Comment by dkanada** [comment] 2019-11-21 08:25
> I vote for #185 to be closed, almost no FLOSS apps, and many of the apps are there anyway.

I don't see any reason to close the issue just because it has several proprietary apps listed, I have added quite a few myself to cover all my icons. We definitely don't have any obligation to add them ourselves though.

**Comment by dkanada** [comment] 2019-11-22 16:12
If you look at the icon list in the app it seems a lot of the new icons aren't properly getting converted with the scripts. Do either of you know what the issue is? I've seen that a few times before but haven't pinned it down.

**Comment by h-bruch** [comment] 2019-11-22 17:08
> I don't see any reason to close the issue just because it has several proprietary apps listed, I have added quite a few myself to cover all my icons. We definitely don't have any obligation to add them ourselves though.

Got it!

> If you look at the icon list in the app it seems a lot of the new icons aren't properly getting converted with the scripts. Do either of you know what the issue is? I've seen that a few times before but haven't pinned it down.

I have two "empty" icons in the list, near the bottom and three slots apart. Are you referring to them? O/w I can't find any flaws. I think they are the unimainz.svg and vanillamusic.svg. unimainz.svg has a mask, that might cause a problem. Not sure about the other one. I will find a bit of time during the weekend and look into it.

**Comment by dkanada** [comment] 2019-11-22 17:28
There are also several white shapes above those two blank icons, they might also be from the mask issue actually. I'm not sure why the raster script doesn'twork with masks but if you can fix that script I'd love to leave them in the SVG files. They're more convenient after all.

**Comment by dkanada** [comment] 2019-12-06 17:47
I'm close to another release, just have to fix any remaining empty or broken icons. Let me know if there are any stray issues I forgot to close, and thanks for adding so many apps!

**Comment by Donnnno** [comment] 2019-12-06 18:13
I added these ones in the last pull requests: #4, #15  #77 #84 #92

**Comment by dkanada** [comment] 2020-01-13 06:13
Let me know if any other issues can be closed at this point.

**Comment by Donnnno** [comment] 2020-01-13 09:56
Hi, #2 #129 #185 and #219 can be closed now that they're added :)

**Comment by dkanada** [comment] 2020-01-13 11:00
There aren't that many open issues now so I no longer think this meta issue is required. If you guys ever finish all the icons in a request just let me know in the issue itself, thanks!

**Closed** 2020-01-13 11:01 UTC
